-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "defending" DOUBLE PRECISION,
ADD COLUMN     "diving" DOUBLE PRECISION,
ADD COLUMN     "dribbling" DOUBLE PRECISION,
ADD COLUMN     "handling" DOUBLE PRECISION,
ADD COLUMN     "kicking" DOUBLE PRECISION,
ADD COLUMN     "pace" DOUBLE PRECISION,
ADD COLUMN     "passing" DOUBLE PRECISION,
ADD COLUMN     "physical" DOUBLE PRECISION,
ADD COLUMN     "positioning" DOUBLE PRECISION,
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN     "reflexes" DOUBLE PRECISION,
ADD COLUMN     "shooting" DOUBLE PRECISION,
ADD COLUMN     "speed" DOUBLE PRECISION;
